// Helper function that turns a function into curried form
function curry(fn){
    let arity = fn.length;
    function worker(f,ar){
        if(ar == 1){return f}
        return worker((...args) => {return (x)=>f(...args.slice(0,ar),x)},ar-1)
    }
    return worker(fn, arity)
}

// multiplay two 3x3 matrix stored in column major order
// auto generated by github co-pilot, need verification
function matmul(A, B){
    var C = new Array(9);
    for(var i = 0; i < 3; i++){
        for(var j = 0; j < 3; j++){
            C[i*3+j] = 0;
            for(var k = 0; k < 3; k++){
                C[i*3+j] += A[i*3+k] * B[k*3+j];
            }
        }
    }
    return C;
}
